# ──────────────────────────────────────────────────────────────────
# Anton Agent - Inventory
# ──────────────────────────────────────────────────────────────────

[anton_agents]
agent1  ansible_host=148.113.4.94 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/cloud_key anton_domain=itsomg.antoncomputer.in
# agent2  ansible_host=203.0.113.20
# agent3  ansible_host=10.0.0.5  ansible_user=ubuntu  ansible_ssh_private_key_file=~/.ssh/other_key

[anton_agents:vars]
; ansible_user=ubuntu
; ansible_ssh_private_key_file=~/.ssh/id_rsa
# anthropic_api_key=sk-ant-api03-xxxxx
braintrust_api_key="sk-XyG9qHFgR6IDMk7XmfSrX0bTbTZIIn00qCevII0qUNQFLykP"
