#!/usr/bin/env node

/**
 * Reads prompts/*.md and generates src/embedded-prompts.ts
 * so the system prompt is baked into the compiled output.
 *
 * Run before `tsc`:
 *   node scripts/embed-prompts.js
 *
 * When bundled with esbuild (binary build), the prompt becomes
 * an inline string — no filesystem read needed at runtime.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse as parseYaml } from 'yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const systemPrompt = readFileSync(join(root, 'prompts', 'system.md'), 'utf-8')

// Load project-type prompt modules
const projectTypesDir = join(root, 'prompts', 'project-types')
const projectTypePrompts = {}
if (existsSync(projectTypesDir)) {
  for (const file of readdirSync(projectTypesDir).filter(f => f.endsWith('.md')).sort()) {
    const name = file.replace('.md', '')
    projectTypePrompts[name] = readFileSync(join(projectTypesDir, file), 'utf-8')
  }
}

// Load reference knowledge modules
const referencesDir = join(root, 'prompts', 'references')
const references = {}
let referencePacks = {}
if (existsSync(referencesDir)) {
  for (const file of readdirSync(referencesDir).filter(f => f.endsWith('.md')).sort()) {
    const name = file.replace('.md', '')
    references[name] = readFileSync(join(referencesDir, file), 'utf-8')
  }
  const packsPath = join(referencesDir, '_packs.yaml')
  if (existsSync(packsPath)) {
    referencePacks = parseYaml(readFileSync(packsPath, 'utf-8'))
  }
}

const output = `// AUTO-GENERATED by scripts/embed-prompts.js — do not edit manually.
// Re-run: node scripts/embed-prompts.js (or pnpm build will do it)

export const EMBEDDED_SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)}

/** Project-type prompt modules — injected when a session is scoped to a typed project. */
export const EMBEDDED_PROJECT_TYPE_PROMPTS: Record<string, string> = ${JSON.stringify(projectTypePrompts, null, 2)}

/** Reference knowledge modules — loaded contextually for coding tasks. */
export const EMBEDDED_REFERENCES: Record<string, string> = ${JSON.stringify(references, null, 2)}

/** Reference packs — groups of related references selected by project type and task. */
export const EMBEDDED_REFERENCE_PACKS: Record<string, { description: string; tags: string[]; refs: string[] }> = ${JSON.stringify(referencePacks, null, 2)}
`

writeFileSync(join(root, 'src', 'embedded-prompts.ts'), output)
console.log('  Generated src/embedded-prompts.ts')
console.log(`  Project type modules: ${Object.keys(projectTypePrompts).join(', ') || '(none)'}`)
console.log(`  References: ${Object.keys(references).join(', ') || '(none)'}`)
console.log(`  Reference packs: ${Object.keys(referencePacks).join(', ') || '(none)'}`)
