#!/usr/bin/env node

/**
 * Reads prompts/*.md and generates src/embedded-prompts.ts
 * so the system prompt is baked into the compiled output.
 *
 * Run before `tsc`:
 *   node scripts/embed-prompts.js
 *
 * When bundled with esbuild (binary build), the prompt becomes
 * an inline string — no filesystem read needed at runtime.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const systemPrompt = readFileSync(join(root, 'prompts', 'system.md'), 'utf-8')

const output = `// AUTO-GENERATED by scripts/embed-prompts.js — do not edit manually.
// Re-run: node scripts/embed-prompts.js (or pnpm build will do it)

export const EMBEDDED_SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)}
`

writeFileSync(join(root, 'src', 'embedded-prompts.ts'), output)
console.log('  Generated src/embedded-prompts.ts')
