/**
 * Desktop app auto-updater using Tauri's built-in updater plugin.
 *
 * This handles updates to the desktop app itself (the .dmg/.msi/.AppImage).
 * Separate from the agent self-update system (which updates the VM binary).
 *
 * Flow:
 *   1. On app startup, check the GitHub Release endpoint for a new version
 *   2. If available, prompt the user
 *   3. Download + install in the background
 *   4. Restart the app
 *
 * The updater checks:
 *   https://github.com/OmGuptaIND/anton.computer/releases/latest/download/latest.json
 *
 * This JSON file is auto-generated by `tauri-action` during CI builds.
 */

import { check } from '@tauri-apps/plugin-updater'
import { relaunch } from '@tauri-apps/plugin-process'

export interface DesktopUpdateState {
  available: boolean
  version: string | null
  downloading: boolean
  progress: number
  error: string | null
}

/**
 * Check for desktop app updates. Call this once on app startup.
 * Returns update info if available, null otherwise.
 */
export async function checkDesktopUpdate(): Promise<{
  version: string
  body: string | null
  install: () => Promise<void>
} | null> {
  try {
    const update = await check()

    if (!update) return null

    return {
      version: update.version,
      body: update.body ?? null,
      install: async () => {
        await update.downloadAndInstall()
        await relaunch()
      },
    }
  } catch (err) {
    console.warn('Desktop update check failed:', err)
    return null
  }
}
